# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x81\x01\n\x0cImageRequest\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x14\n\x0coverlap_data\x18\x03 \x01(\x0c\x12\x16\n\x0eoverlap_blocks\x18\x04 \x01(\x0c\x12\x0f\n\x07task_id\x18\x05 \x01(\t\x12\x13\n\x0bsharing_box\x18\x06 \x01(\x0c\"1\n\rResultRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07results\x18\x02 \x01(\x0c\x32\x8e\x01\n\x07Greeter\x12?\n\tSendImage\x12\x18.helloworld.ImageRequest\x1a\x16.helloworld.HelloReply\"\x00\x12\x42\n\x0bSendResults\x12\x19.helloworld.ResultRequest\x1a\x16.helloworld.HelloReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_IMAGEREQUEST = DESCRIPTOR.message_types_by_name['ImageRequest']
_RESULTREQUEST = DESCRIPTOR.message_types_by_name['ResultRequest']
HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

ResultRequest = _reflection.GeneratedProtocolMessageType('ResultRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESULTREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.ResultRequest)
  })
_sym_db.RegisterMessage(ResultRequest)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _HELLOREPLY._serialized_start=32
  _HELLOREPLY._serialized_end=61
  _IMAGEREQUEST._serialized_start=64
  _IMAGEREQUEST._serialized_end=193
  _RESULTREQUEST._serialized_start=195
  _RESULTREQUEST._serialized_end=244
  _GREETER._serialized_start=247
  _GREETER._serialized_end=389
# @@protoc_insertion_point(module_scope)
